import pandas as pd
import os
import glob
import json
import logging
from email.message import EmailMessage
import smtplib


os.makedirs("Logs", exist_ok=True)  #create log folder if not exist

logging.basicConfig(
    filename="Logs/automation.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logging.info("Weekly report generation started")




try:

    DATA_FOLDER = "recieved_metrics"

    # Read all CSV files
    all_files = glob.glob(os.path.join(DATA_FOLDER, "*.csv"))

    df_list = []
    for file in all_files:
        df = pd.read_csv(file)
        df_list.append(df)

    data = pd.concat(df_list, ignore_index=True)

    # Convert timestamp
    data['timestamp'] = pd.to_datetime(data['timestamp'])
    data['date'] = data['timestamp'].dt.date



    # Extract disk JSON
    def extract_disk_info(row):
        disk_list = json.loads(row)
        total = 0
        used = 0
        free = 0
        for disk in disk_list:
            total += disk['total_gb']
            used += disk['used_gb']
            free += disk['free_gb']
        return pd.Series([total, used, free])

    data[['disk_total_gb', 'disk_used_gb', 'disk_free_gb']] = \
        data['disk_info_json'].apply(extract_disk_info)



    servers = data['server_name'].unique()


    for server in servers:
        
        
        server_data = data[data['server_name'] == server].copy()
        server_data = server_data.sort_values('timestamp')
        
        #CPU
        cpu_daily = server_data.groupby('date')['cpu_percent'].agg(['mean', 'max'])
        cpu_daily.rename(columns={
            'mean': 'avg_cpu_percent',
            'max': 'peak_cpu_percent'
        }, inplace=True)
        

        
        #MEMORY
        memory_daily = server_data.groupby('date').agg({
            'total_ram_gb': 'mean',
            'used_ram_gb': 'mean',
            'available_ram_gb': 'mean',
            'ram_percent': 'mean'
        })
        
        memory_daily.rename(columns={
            'ram_percent': 'avg_ram_percent'
        }, inplace=True)

        
        #DISK
        disk_daily = server_data.groupby('date')[[
            'disk_total_gb',
            'disk_used_gb',
            'disk_free_gb'
        ]].mean()

        







    html_body = ""

    for server in servers:
        server_data = data[data['server_name'] == server].copy()
        server_data = server_data.sort_values('timestamp')

        cpu_daily = server_data.groupby('date')['cpu_percent'].agg(['mean', 'max'])
        cpu_daily.rename(columns={
            'mean': 'avg_cpu_percent',
            'max': 'peak_cpu_percent'
        }, inplace=True)

        memory_daily = server_data.groupby('date').agg({
            'total_ram_gb': 'mean',
            'used_ram_gb': 'mean',
            'available_ram_gb': 'mean',
            'ram_percent': 'mean'
        })

        memory_daily.rename(columns={
            'ram_percent': 'avg_ram_percent'
        }, inplace=True)

        disk_daily = server_data.groupby('date')[[
            'disk_total_gb',
            'disk_used_gb',
            'disk_free_gb'
        ]].mean()

        html_body += f"""
        <div class="card">
            <h2>Server: {server}</h2>

            <h3>CPU Utilization</h3>
            {cpu_daily.reset_index().to_html(index=False, border=0)}

            <h3>Memory Utilization</h3>
            {memory_daily.reset_index().to_html(index=False, border=0)}

            <h3>Disk Utilization</h3>
            {disk_daily.reset_index().to_html(index=False, border=0)}
        </div>
        """

    html = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial;
                background: #f4f6f8;
            }}
            .card {{
                background: white;
                padding: 20px;
                border-radius: 10px;
                margin-bottom: 20px;
            }}
            table {{
                border-collapse: collapse;
                width: 100%;
            }}
            th, td {{
                border: 1px solid #ddd;
                padding: 8px;
                text-align: center;
            }}
            th {{
                background-color: #1f2937;
                color: white;
            }}
            h1 {{
                color: #1f2937;
            }}
            h2 {{
                background: #48668C;
                color: white;
            }}
            .footer {{
                font-size: 12px;
                color: gray;
            }}
        </style>
    </head>
    <body>
        <h1>Weekly Server Utilization Report</h1>
        {html_body}
        <p class="footer">
            This is an automated weekly infrastructure report.<br>
            Generated by Python Automation System.
        </p>
    </body>
    </html>
    """






    SENDER_EMAIL = "ravindu.01999@gmail.com"
    APP_PASSWORD = "app password here"
    RECEIVER_EMAIL = "ravindu0032@gmail.com"

    msg = EmailMessage()
    msg["Subject"] = "Weekly Server Utilization Report"
    msg["From"] = SENDER_EMAIL
    msg["To"] = RECEIVER_EMAIL

    msg.set_content("HTML email required")
    msg.add_alternative(html, subtype="html")

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(SENDER_EMAIL, APP_PASSWORD)
        server.send_message(msg)















    logging.info("Weekly report generation successful\n")

except Exception as e:
    logging.error(f"Weekly report generation failed: {e}\n")
    raise